### ISSUE TITLE
Add a checklist for tests

### ISSUE THREAD

**Issue by hodovani** [hodovani/hodovani.github.io#2]

**Comment by hodovani** [comment]
- [ ] Have a test coverage report.
- [ ] Test app is run without errors.
- [ ] Test app initial state looks right. 
- [ ] All pure functions had tests.

**Comment by hodovani** [comment]
Created a draft here https://github.com/hodovani/hodovani.github.io/blob/master/posts/test-checklist.md
