### ISSUE TITLE
Article checklist WIP

### ISSUE THREAD

**Issue by hodovani** [hodovani/hodovani.github.io#20]
#### Type
- Tutorial: How do I do a particular task? This kind of post shows you how to make something, with step-by-step instructions. But a good tutorial has more than steps. Does it introduce the topic? Does it tell you why you might use this particular solution? Does it have enough screenshots and code samples? Does it include a demo of the result in action?
- Explainer: What is this concept about, and how would I use it? This kind of post takes a step back and gives us the big picture, tells us why the topic is important, where it came from, and then zooms in to show an example or two of what it looks like in real life. Explainers also typically share when we'd actually use the concept described. Good explainers don't get lost in the terminology or examples. They're an accessible explanation of how something works and why it matters.
- Project: How did you make this, and what did you learn while making it? This kind of post breaks down a project you created, but instead of focusing on the steps (as seen in tutorials), it focuses on your journey building it. It usually starts with what the project is and why you created it. It has some screenshots and a link to the live project. But it also includes some technical challenges you had along the way, how you overcame them, and what you learned.

#### Structure
- [ ] Title
    https://coschedule.com/headline-analyzer
    Capitalize the first letter of every word except articles, coordinating conjunctions, and prepositions of three letters or fewer
    The more emotional (positive or negative) a headline is, the more likely people will click it
    Make sure the headline is 80 characters or fewer(8-14 words)
    The more emotional (positive or negative) a headline is, the more likely people will click it
    Don’t use curiosity gap clickbait
    
- [ ] Cover image
    Use an image aspect ratio of 1.91:1
    Image source https://www.pexels.com
    
- [ ] Introduction. This section describes the content at a high level. It can be an initial paragraph or a Tl;DR section explaining what you plan to cover in the article.

- [ ] Headings and Sub Headings: You should break the content into logical sub-topics. To do that, create sections and provide relevant headings and sub-headings. You should break up long stories with images. The text should start making points and telling a story immediately

- [ ] Summary: A summary section at the end helps your reader recap what they have learned from the article so far. It is also helpful for a returning reader to recollect the content by going through the summary.
    Ask an open question at the end
    
- [ ] Important Links: You may want to end your article with a list of related links for further reading. You can use the same section to list the links to your previously published articles as well.

- [ ] CTA. Button to say thanks it twitter or other platform.

- [ ] Meta:
    Canonical URL
    5 tags

#### Tools
- [ ] https://www.grammarly.com
- [ ] https://hemingwayapp.com
- [ ] https://www.onlinecorrection.com
- [ ] https://github.com/amperser/proselint/
- [ ] https://languagetool.org
- [ ] https://www.expresso-app.org
- [ ] https://editor.typely.com
- [ ] https://editsaurus.tylerwalters.com
- [ ] https://textlint.github.io
- [ ] https://github.com/defmethodinc/just-not-sorry
- [ ] https://www.canva.com/en_gb/
- [ ] [OBS Studio](https://obsproject.com/download)
- [ ] [SERP Snippet Generator](https://serpsim.com)

#### Share platforms
- [ ] Twitter
- [ ] LinkedIn
- [ ] Reddit
- [ ] HackerNews
- [ ] FaceBook
- [ ] EchoJS
- [ ] https://www.instagram.com
- [ ] https://in.pinterest.com
- [ ] Dev.to
- [ ] hashnode
- [ ] medium
- [ ] https://webtoolsweekly.com/archive

#### Headline structures that work well for deep technical articles:
- "How to fix…"
- "How to build…"
- “How to [task] with [tool]”
- "How [something] works"
- "The [adjective] guide to…"
- “What is a [noun]? In English, please.”
- “What exactly is [noun]?”
- “Why [something] matters.”
- “Learn [something] in N hours”
- "A history of [something]”
- “The story behind [something]”

#### Headlines structures that work well for personal narratives
- "How I [did something]"
- “I [did something]. Here’s what I learned.”
- “How I went from [something] to [something] in N years”
- “Why I started [something]”
- “I’ll never [something] again. Here’s why.”
- “How I [did something] without [something]”
- "Why I don’t [something] anymore"

#### Other
- [ ] Substance. Will they walk away with something useful?
- [ ] Be Succinct
- [ ] Make use of lists
- [ ] Use Active Voice
- [ ] Focus on deleting unnecessary words
- [ ] Remove "there is" and "there are"
- [ ] Accessibility. The story should be as easy for a layperson to understand as possible.
- [ ] Brevity. People are busy. A story should be as short as possible, but no shorter.
- [ ] Don’t use listicle headlines, and generally avoid articles structured as lists
- [ ] Use “for example” instead of “E.G.”
- [ ] Use “that is” instead of “I.E.”
- [ ] Use “note that” instead of “N.B.”
- [ ] analogies simple and idiom free
- [ ] Instead of ending lists with “etc.” start them with “like”: “Elvis eats food like bread, peanut butter, and bananas.”
- [ ] Before you publish a story, I recommend you sleep, wake up, then proof-read it again.
- [ ] Write longer comprehensive articles instead of multi-part articles. When people see that an article is long, they’ll often assume the article is serious and comprehensive.

#### Guest post publishers

- https://envato.formstack.com/forms/create_a_tutorial
- https://css-tricks.com/guest-posting/
- https://www.smashingmagazine.com/write-for-us/
- https://betterprogramming.pub/write-for-us-5c4bcba59397

#### Pay for Articles
- https://www.digitalocean.com/community/pages/write-for-digitalocean 👌 
- https://www.techopedia.com/about/contributors 👌 
- https://www.sitepoint.com/write-for-us/ 👌 
- https://alistapart.com/about/contribute/ 👌 can help with editing
- https://code.tutsplus.com/articles/call-for-authors-write-for-tuts--cms-22034 👌 
- https://blog.logrocket.com/become-a-logrocket-guest-author-7d970eb673f9/ 👍 can write about JS
- https://css-tricks.com/guest-posting/ 👌 
- https://draft.dev/write ?
- https://learn.vonage.com/spotlight/ 👌 need to use Vonage
- https://go.twilio.com/twilio-voices/ 👌 need to use Twilio API
- https://www.tutorialspoint.com/about/tutorials_writing.htm 👌 
- https://neptune.ai/write-for-us 👌 
- https://auth0.com/apollo-program 👌 Closed at the moment. Write about electron 

Sources:
https://www.freecodecamp.org/news/the-freecodecamp-medium-publication-editor-handbook-cb5876d1ef23/
https://www.freecodecamp.org/news/technical-blogging-basics/
https://www.freecodecamp.org/news/developer-news-style-guide/
https://www.freecodecamp.org/news/how-to-grow-your-audience-and-share-your-content-with-the-world/

Source to read:
https://developers.google.com/tech-writing
https://www.writethedocs.org/guide/

**Comment by hodovani** [comment]
https://www.indiehackers.com/post/here-are-my-top-tips-for-writing-editing-articles-what-are-yours-12964aa161
